controller_list:
  - name: fake_manipulator_controller
    joints:
      - a1_joint
      - a2_joint
      - a3_joint
      - a4_joint
      - a5_joint
      - a6_joint
  - name: fake_endeffector_controller
    joints:
      []
